CREATE TABLE IF NOT EXISTS regions (
id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK UNIQUE ON CONFLICT ROLLBACK,
name STRING (128) UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK
);

CREATE TABLE IF NOT EXISTS villages (
id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK,
region_id INTEGER REFERENCES regions (id) ON DELETE CASCADE NOT NULL ON CONFLICT ROLLBACK,
name STRING (128) UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK
);

CREATE TABLE IF NOT EXISTS comments (
id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK UNIQUE ON CONFLICT ROLLBACK,
region_id INTEGER REFERENCES regions (id) NOT NULL ON CONFLICT ROLLBACK,
village_id INTEGER REFERENCES villages (id) NOT NULL ON CONFLICT ROLLBACK,
user_name STRING (128) NOT NULL ON CONFLICT ROLLBACK,
user_last_name STRING (64),
user_email STRING (128) NOT NULL ON CONFLICT ROLLBACK,
user_phone STRING (10), comment TEXT (2048) NOT NULL ON CONFLICT ROLLBACK,
pub_datetime DATETIME NOT NULL ON CONFLICT ROLLBACK DEFAULT (datetime('now', 'localtime'))
);
